services:
  nginx-proxy:
    container_name: nginx
    image: nginx
    volumes:
       - ./nginx/templates:/etc/nginx/templates
       - ./nginx/html:/usr/share/nginx/html
       - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
       - "80:80"
       - "443:443"
       - "7000:7000"
       - "7022:7022"
    restart: unless-stopped
